### ISSUE TITLE
which engine version this project work on ?

### ISSUE THREAD

**Issue by RainStone1988** [iniside/ActionRPGGame#16]
hi, guys,
i just opened up the .uproject, and noticed the engine version like this:
"EngineAssociation": "{C19309FF-49B1-44A8-E307-2B81122303E8}",

what's this meaning?
which engine version should i use?

**Comment by iniside** [comment]
I usually try to keep it working with Master for github. 
You might try to make it work with launcher version, but it probabaly wont :).
