### ISSUE TITLE
missing AFBlueprintFunctionLibrary.h

### ISSUE THREAD

**Issue by fangguanya** [iniside/ActionRPGGame#17]
Thanks for your sharing.
But I fetch the latest master branch code, and run with Unreal Engine version 4.18 , but it throw a compile error 

D:\ue4\ActionRPGGame\Plugins\AbilityFramework\Source\AbilityFrameworkEditor\AFEK2Node_AsyncEffectTaskCall.cpp(7): fatal error C1083: ?޷???????ļ?: ??AFBlueprintFunctionLibrary.h??: No such file or directory

how can I get this source file?

**Comment by Gregan321** [comment]
I know I"m not the owner of this thing, but if you just want it to get running, try commenting out the Include on it. I hope Iniside can update the Master Branch with this file soon....

**Comment by fangguanya** [comment]
@Gregan321 Thanks, I just try it out, it works!
