### ISSUE TITLE
Cannot Compile against 4.7.3

### ISSUE THREAD

**Issue by Chaos192** [iniside/ActionRPGGame#6]
http://i.gyazo.com/560c6bc572ed795dbc18acacd1760169.png
http://i.gyazo.com/308b0627528dbe566048502142bd71da.png
http://i.gyazo.com/c8a9af2dfd13ce14e69d029c3f71c1c2.png
http://i.gyazo.com/5f810793a3666b553926bfcae57e4b81.png

So that is what I get every single time, it is unable to find any of the includes >.>

**Comment by iniside** [comment]
Did you tried to rebuild from Visual Studio ?
That missing ActionRPGGame.h header is really baffling, you can see it is in repo here:
https://github.com/iniside/ActionRPGGame/tree/master/Source/ActionRPGGame/Public

**Comment by Chaos192** [comment]
Yeah I tried it every way i could think, I changed build settings and I get the error of it missing the headers and if I do nothing to it but hit rebuild then I get the same error as before and yes I am using Visual studio 2013 ultimate edition. I really do not get what is missing but I either get this error:
http://i.gyazo.com/5f810793a3666b553926bfcae57e4b81.png

or this one:
http://i.gyazo.com/c8a9af2dfd13ce14e69d029c3f71c1c2.png

In visual studio and the first one doesn't make sense since all the headers are there and the second one is the same error I had before.

**Comment by iniside** [comment]
Can you post output log ?

I cloned repo, and I have error, but it is related to some part of engine concerning AI, for whatever reason 0o.

**Comment by Chaos192** [comment]
Okay I was playing with it again and it had the .generated.h after the names of the .h files it couldn't find so I removed the .generated part and this is what I get now:

1>------ Rebuild All started: Project: ActionRPGGame, Configuration: Development_Editor x64 ------
1>  Cleaning ActionRPGGameEditor Binaries...
1>  Parsing headers for ActionRPGGameEditor
1>C:/Users/Chaos/Documents/Unreal Projects/ActionRPGGame_/Source/GameInterfaces/IGIInput.h(6): error : Class 'UIGIInput' contains a dependency (#include or DependsOn) to itself
1>C:/Users/Chaos/Documents/Unreal Projects/ActionRPGGame_/Source/GameInterfaces/IGIInteractable.h(8): error : Class 'UIGIInteractable' contains a dependency (#include or DependsOn) to itself
1>C:/Users/Chaos/Documents/Unreal Projects/ActionRPGGame_/Source/GameInterfaces/IGIPawn.h(9): error : Class 'UIGIPawn' contains a dependency (#include or DependsOn) to itself
1>C:/Users/Chaos/Documents/Unreal Projects/ActionRPGGame_/Source/GameInterfaces/IGISkeletalMesh.h(6): error : Class 'UIGISkeletalMesh' contains a dependency (#include or DependsOn) to itself
1>C:/Users/Chaos/Documents/Unreal Projects/ActionRPGGame_/Source/GameInterfaces/IGISocket.h(6): error : Class 'UIGISocket' contains a dependency (#include or DependsOn) to itself
1>Error : Failed to generate code for ActionRPGGameEditor - error code: OtherCompilationError (2)
1>  UnrealHeaderTool failed for target 'ActionRPGGameEditor' (platform: Win64, module info: C:\Users\Chaos\Documents\Unreal Projects\ActionRPGGame_\Intermediate\Build\Win64\ActionRPGGameEditor\Development\UnrealHeaderTool.manifest).
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.MakeFile.Targets(43,5): error MSB3073: The command ""C:\Program Files\Epic Games\4.7\Engine\Build\BatchFiles\Rebuild.bat" ActionRPGGameEditor Win64 Development "C:\Users\Chaos\Documents\Unreal Projects\ActionRPGGame_\ActionRPGGame.uproject" -rocket" exited with code 2.
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by iniside** [comment]
Ok. I dunno if this wil help you, since I just can't reproduce your log but:
1. Clone repository again.
2. Right click on uproject file, and select switch unreal engine version, and select binary 4.7.
3. Open project in visual studio.
4. Right click on ActionRPGGame, go to properties, go to NMake, and and here wiill be general.
If there find ActionRPGGameEditor, and replace it with ActionRPGGame.

It seems, to helped resolved the issues I had. It might or might not be related though. Now I'm trying to figure out, why wrong command lines were generated in first place..

**Comment by Chaos192** [comment]
Okay that worked thanks man :)

**Comment by iniside** [comment]
Bah it doesn't work ;) It build an Game Build, not editor build, so you still won't be able to run editor.

I'm still trying to figure out why it doesn't compile against binary version.

In mean while I'm sure it will work against latest source 4.7 source.

**Comment by Chaos192** [comment]
Ah yeah I see what you are saying now, it does make an game build but that fails to launch lol.. But at least there aren't any errors for that, only thing left is fixing it to work on editor build. There is a 3DBuzz tutorial for creating plugins for UE4 so I will be watching that.

**Comment by iniside** [comment]
Hey

If you are still interested I think i fixed the issues finally. Or so it seems at least.

**Comment by Chaos192** [comment]
I will check it out thanks, hopefully it builds as an editor build and not a game build.

**Comment by Chaos192** [comment]
Sorry man it gives the same issue as before and you have to manually go in and remove the "Editor" part in NMake like before.

**Comment by henrya2** [comment]
I got the same issue as you.
I use binary version 4.7.3.

**Comment by iniside** [comment]
Sorry but ut iż impossiblie to compile against kaunxher version. You must
use source from github. There is bug in binarny which prevents it grom
working.

https://answers.unrealengine.com/questions/197139/unparsed-class-found-while-validating-dependson-en.html

**Comment by iniside** [comment]
Lol sorry for last message I was writing from tablet had wrong language
setup, and auto correct I on kicked in.

Sorry but it is impossiblie to compile against launcher version. You must
use source from github. There is bug in binarny which prevents it from
working.

https://answers.unrealengine.com/questions/197139/unparsed-class-found-while-validating-dependson-en.html
