### ISSUE TITLE
Player Controller & Character BP

### ISSUE THREAD

**Issue by Chaos192** [iniside/ActionRPGGame#8]
Hey do you mind sharing screenshots of your set up for inventory and such? cause they are all broken and idk what you were casting to..

**Comment by heero7** [comment]
Hey bud sorry, I got this setup from another repo. He hasn't touched it
since. Sorry man

**Comment by Chaos192** [comment]
well know how to do that stuff? cause I got everything but the UI working properly and for the life of me idk what he did.
