### ISSUE TITLE
can't comile in 4.10

### ISSUE THREAD

**Issue by nneesshh** [iniside/ActionRPGGame#9]
It misses all widgets in put in BasePlayerController blueprint, such as health bar, stamina bar, etc.
May it lack of some resources?

**Comment by zimzimdz** [comment]
Here is the compile result og commit 113:

Severity	Code	Description	Project	File	Line
Error	LNK1120	2 unresolved externals	ActionRPGGame	G:\Project\RPGFramework\Binaries\Win64\UE4Editor-GameAttributes.dll	1
Error	LNK1120	2 unresolved externals	ActionRPGGame	G:\Project\RPGFramework\Binaries\Win64\UE4Editor-GameInterfaces.dll	1
Error	LNK1120	2 unresolved externals	ActionRPGGame	G:\Project\RPGFramework\Binaries\Win64\UE4Editor-GameWidgets.dll	1
Error		Failed to produce item: G:\Project\RPGFramework\Binaries\Win64\UE4Editor-GameInterfaces.dll	ActionRPGGame	G:\Project\RPGFramework\Intermediate\ProjectFiles\ERROR	1
Error	MSB3073	The command ""C:\Program Files\Epic Games\4.10\Engine\Build\BatchFiles\Build.bat" ActionRPGGameEditor Win64 Development "G:\Project\RPGFramework\ActionRPGGame.uproject" -rocket -waitmutex" exited with code -1.	ActionRPGGame	C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.MakeFile.Targets	38
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: static class TBaseDelegate<class UObjectBase * * *> & __cdecl FCoreDelegates::GetObjectArrayForDebugVisualizersDelegate(void)" (__imp_?GetObjectArrayForDebugVisualizersDelegate@FCoreDelegates@@SAAEAV?$TBaseDelegate@PEAPEAPEAVUObjectBase@@$$$V@@XZ) referenced in function "void __cdecl `dynamic initializer for 'GObjectArrayForDebugVisualizers''(void)" (??__EGObjectArrayForDebugVisualizers@@YAXXZ)	ActionRPGGame	G:\Project\RPGFramework\Intermediate\ProjectFiles\GameAttributes.cpp.obj	1
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: static class TBaseDelegate<class UObjectBase * * *> & __cdecl FCoreDelegates::GetObjectArrayForDebugVisualizersDelegate(void)" (__imp_?GetObjectArrayForDebugVisualizersDelegate@FCoreDelegates@@SAAEAV?$TBaseDelegate@PEAPEAPEAVUObjectBase@@$$$V@@XZ) referenced in function "void __cdecl `dynamic initializer for 'GObjectArrayForDebugVisualizers''(void)" (??__EGObjectArrayForDebugVisualizers@@YAXXZ)	ActionRPGGame	G:\Project\RPGFramework\Intermediate\ProjectFiles\GameInterfaces.cpp.obj	1
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: static class TBaseDelegate<class UObjectBase * * *> & __cdecl FCoreDelegates::GetObjectArrayForDebugVisualizersDelegate(void)" (__imp_?GetObjectArrayForDebugVisualizersDelegate@FCoreDelegates@@SAAEAV?$TBaseDelegate@PEAPEAPEAVUObjectBase@@$$$V@@XZ) referenced in function "void __cdecl `dynamic initializer for 'GObjectArrayForDebugVisualizers''(void)" (??__EGObjectArrayForDebugVisualizers@@YAXXZ)	ActionRPGGame	G:\Project\RPGFramework\Intermediate\ProjectFiles\GameWidgets.cpp.obj	1
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: static class TBaseDelegate<int * * *> & __cdecl FCoreDelegates::GetSerialNumberBlocksForDebugVisualizersDelegate(void)" (__imp_?GetSerialNumberBlocksForDebugVisualizersDelegate@FCoreDelegates@@SAAEAV?$TBaseDelegate@PEAPEAPEAH$$$V@@XZ) referenced in function "void __cdecl `dynamic initializer for 'GSerialNumberBlocksForDebugVisualizers''(void)" (??__EGSerialNumberBlocksForDebugVisualizers@@YAXXZ)	ActionRPGGame	G:\Project\RPGFramework\Intermediate\ProjectFiles\GameAttributes.cpp.obj	1
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: static class TBaseDelegate<int * * *> & __cdecl FCoreDelegates::GetSerialNumberBlocksForDebugVisualizersDelegate(void)" (__imp_?GetSerialNumberBlocksForDebugVisualizersDelegate@FCoreDelegates@@SAAEAV?$TBaseDelegate@PEAPEAPEAH$$$V@@XZ) referenced in function "void __cdecl `dynamic initializer for 'GSerialNumberBlocksForDebugVisualizers''(void)" (??__EGSerialNumberBlocksForDebugVisualizers@@YAXXZ)	ActionRPGGame	G:\Project\RPGFramework\Intermediate\ProjectFiles\GameInterfaces.cpp.obj	1
Error	LNK2019	unresolved external symbol "__declspec(dllimport) public: static class TBaseDelegate<int * * *> & __cdecl FCoreDelegates::GetSerialNumberBlocksForDebugVisualizersDelegate(void)" (__imp_?GetSerialNumberBlocksForDebugVisualizersDelegate@FCoreDelegates@@SAAEAV?$TBaseDelegate@PEAPEAPEAH$$$V@@XZ) referenced in function "void __cdecl `dynamic initializer for 'GSerialNumberBlocksForDebugVisualizers''(void)" (??__EGSerialNumberBlocksForDebugVisualizers@@YAXXZ)	ActionRPGGame	G:\Project\RPGFramework\Intermediate\ProjectFiles\GameWidgets.cpp.obj	1

**Comment by iniside** [comment]
Did you tried compiling with github sources ?
I do not test on launcher version of engine, and frankly the fact it is not working with launcher binaries is to be expected.

Locally I use promoted branch and compile against it.

**Comment by zimzimdz** [comment]
I don't use engine binaries but full sources. I've my local clone of your project, opened it in VS2015 and it doesn't compile.
Just try on your side to clone the sources somewhere else, open the uproject with UE4, it will try to compile, fail and ask to do it manually. Which will fail as well.

**Comment by iniside** [comment]
Well I cloned and compiled successfully against promoted branch from github and then launched it.
It indeed asked me about missing modules, so I cliked yes to rebuild it, it log it showed tareget is up to date, and then launched.

You forget to change uproject engine location ?

**Comment by zimzimdz** [comment]
"Well I cloned and compiled" UE4 or this project ?

**Comment by nneesshh** [comment]
Hi, many thanks to you guys. My c++ sln compling is OK, but i can't lauch the project from UE4 editor, It looks like missing some ui widgets, such as health bar, stamina bar, and missing some blueprints parent class, such as BP_Ambient EffectManager, BP_GDCGameMode, MyPC. Their parents come from kitedemo, should I install kitedemo first? Where could I find those UIs?

**Comment by nneesshh** [comment]
PS. my ue4 is compiled from source by vs2015, and its version is 4.10.

**Comment by iniside** [comment]
Of course this project.
Looking at your output log you are trying to compile against launcher version of engine.

**Comment by zimzimdz** [comment]
I grab latest engine sources, compile, run and compile your sources which succeeded.
Thanks

**Comment by nneesshh** [comment]
Hi, iniside, thank you for your reply.
I am a ue4 starter, and I am looking for an inventory project to study. Can you make a demo project of your Inventory System including a sample UI, just like your youtube video? I just can't find it anywhere.
